import type { DomainContent } from "../types/contribute.types"
import type { Video } from "../types/videos.types"



export const mockVideos: Video[] = [
    {
        id: "1",
        title: "JavaScript Hoisting Explained Simply",
        description: "Understand how hoisting works in JavaScript with clear examples.",
        thumbnail: "https://picsum.photos/400/225",
        videoUrl: "https://www.youtube.com/watch?v=Fnlnw8uY6jo",
        duration: "8:24",
        rating: 4.6,
        views: 12000,
        upvotes: 320,
        downvotes: 18,
        tags: ["javascript", "hoisting", "basics"],
        author: "OpenCourse",
    },
    {
        id: "2",
        title: "Closures in JavaScript (Visual Guide)",
        description: "A visual and intuitive explanation of closures in JavaScript.",
        thumbnail: "https://picsum.photos/401/225",
        videoUrl: "https://www.youtube.com/watch?v=3a0I8ICR1Vg",
        duration: "12:10",
        rating: 4.8,
        views: 9800,
        upvotes: 410,
        downvotes: 12,
        tags: ["javascript", "closures", "advanced"],
        author: "Community",
    },
    {
        id: "3",
        title: "Event Loop Explained",
        description: "Deep dive into JavaScript event loop, call stack, and queue.",
        thumbnail: "https://picsum.photos/402/225",
        videoUrl: "https://www.youtube.com/watch?v=8aGhZQkoFbQ",
        duration: "10:45",
        rating: 4.7,
        views: 15000,
        upvotes: 500,
        downvotes: 20,
        tags: ["javascript", "event-loop"],
        author: "OpenCourse",
    },
    {
        id: "4",
        title: "Promises vs Async/Await",
        description: "Learn the difference between Promises and async/await.",
        thumbnail: "https://picsum.photos/403/225",
        videoUrl: "https://www.youtube.com/watch?v=V_Kr9OSfDeU",
        duration: "9:30",
        rating: 4.5,
        views: 11000,
        upvotes: 300,
        downvotes: 15,
        tags: ["javascript", "async"],
        author: "Community",
    },
    {
        id: "5",
        title: "JavaScript Array Methods You Must Know",
        description: "map, filter, reduce explained with examples.",
        thumbnail: "https://picsum.photos/404/225",
        videoUrl: "https://www.youtube.com/watch?v=R8rmfD9Y5-c",
        duration: "14:12",
        rating: 4.9,
        views: 21000,
        upvotes: 780,
        downvotes: 9,
        tags: ["javascript", "arrays"],
        author: "OpenCourse",
    },
    {
        id: "6",
        title: "React Hooks Crash Course",
        description: "useState, useEffect, and custom hooks explained.",
        thumbnail: "https://picsum.photos/405/225",
        videoUrl: "https://www.youtube.com/watch?v=TNhaISOUy6Q",
        duration: "16:20",
        rating: 4.8,
        views: 18000,
        upvotes: 620,
        downvotes: 11,
        tags: ["react", "hooks"],
        author: "OpenCourse",
    },
    {
        id: "7",
        title: "useEffect in Depth",
        description: "Master side effects in React using useEffect.",
        thumbnail: "https://picsum.photos/406/225",
        videoUrl: "https://www.youtube.com/watch?v=0ZJgIjIuY7U",
        duration: "11:50",
        rating: 4.6,
        views: 9000,
        upvotes: 260,
        downvotes: 14,
        tags: ["react", "useEffect"],
        author: "Community",
    },
    {
        id: "8",
        title: "React State Management Explained",
        description: "State, props, and lifting state up.",
        thumbnail: "https://picsum.photos/407/225",
        videoUrl: "https://www.youtube.com/watch?v=35lXWvCuM8o",
        duration: "13:05",
        rating: 4.7,
        views: 12500,
        upvotes: 390,
        downvotes: 16,
        tags: ["react", "state"],
        author: "OpenCourse",
    },
    {
        id: "9",
        title: "What is REST API?",
        description: "Understand REST APIs and HTTP methods.",
        thumbnail: "https://picsum.photos/408/225",
        videoUrl: "https://www.youtube.com/watch?v=Q-BpqyOT3a8",
        duration: "9:00",
        rating: 4.4,
        views: 8500,
        upvotes: 210,
        downvotes: 19,
        tags: ["backend", "api"],
        author: "Community",
    },
    {
        id: "10",
        title: "Node.js Crash Course",
        description: "Learn Node.js fundamentals in one video.",
        thumbnail: "https://picsum.photos/409/225",
        videoUrl: "https://www.youtube.com/watch?v=fBNz5xF-Kx4",
        duration: "18:40",
        rating: 4.8,
        views: 19500,
        upvotes: 700,
        downvotes: 10,
        tags: ["nodejs", "backend"],
        author: "OpenCourse",
    },
    {
        id: "11",
        title: "Express.js Basics",
        description: "Routing, middleware, and APIs with Express.",
        thumbnail: "https://picsum.photos/410/225",
        videoUrl: "https://www.youtube.com/watch?v=L72fhGm1tfE",
        duration: "15:10",
        rating: 4.6,
        views: 10200,
        upvotes: 330,
        downvotes: 13,
        tags: ["express", "backend"],
        author: "Community",
    },
    {
        id: "12",
        title: "MongoDB for Beginners",
        description: "Learn MongoDB basics and CRUD operations.",
        thumbnail: "https://picsum.photos/411/225",
        videoUrl: "https://www.youtube.com/watch?v=ofme2o29ngU",
        duration: "14:55",
        rating: 4.5,
        views: 8700,
        upvotes: 280,
        downvotes: 17,
        tags: ["mongodb", "database"],
        author: "OpenCourse",
    },
    {
        id: "13",
        title: "Git & GitHub Explained",
        description: "Version control basics with Git and GitHub.",
        thumbnail: "https://picsum.photos/412/225",
        videoUrl: "https://www.youtube.com/watch?v=RGOj5yH7evk",
        duration: "10:30",
        rating: 4.9,
        views: 22000,
        upvotes: 820,
        downvotes: 6,
        tags: ["git", "github"],
        author: "OpenCourse",
    },
    {
        id: "14",
        title: "System Design Basics",
        description: "Learn scalability, load balancing, and caching.",
        thumbnail: "https://picsum.photos/413/225",
        videoUrl: "https://www.youtube.com/watch?v=MbjObHmDbZo",
        duration: "17:00",
        rating: 4.7,
        views: 16000,
        upvotes: 540,
        downvotes: 22,
        tags: ["system-design"],
        author: "Community",
    },
    {
        id: "15",
        title: "Docker Explained Simply",
        description: "Containers, images, and Docker workflow.",
        thumbnail: "https://picsum.photos/414/225",
        videoUrl: "https://www.youtube.com/watch?v=Gjnup-PuquQ",
        duration: "12:40",
        rating: 4.6,
        views: 14000,
        upvotes: 460,
        downvotes: 18,
        tags: ["docker", "devops"],
        author: "OpenCourse",
    },
];

export const nonTechVideos: Video[] = [
    {
        id: "n1",
        title: "Effective Communication Skills",
        description: "Learn how to communicate clearly and confidently.",
        thumbnail: "https://picsum.photos/500/225",
        videoUrl: "https://www.youtube.com/watch?v=HAnw168huqA",
        duration: "10:15",
        rating: 4.7,
        views: 18000,
        upvotes: 560,
        downvotes: 14,
        tags: ["communication", "soft-skills"],
        author: "OpenCourse",
    },
    {
        id: "n2",
        title: "Public Speaking for Beginners",
        description: "Overcome stage fear and speak with confidence.",
        thumbnail: "https://picsum.photos/501/225",
        videoUrl: "https://www.youtube.com/watch?v=UF8uR6Z6KLc",
        duration: "12:40",
        rating: 4.6,
        views: 15000,
        upvotes: 480,
        downvotes: 20,
        tags: ["public-speaking", "confidence"],
        author: "Community",
    },
    {
        id: "n3",
        title: "Time Management Mastery",
        description: "Techniques to manage time and increase productivity.",
        thumbnail: "https://picsum.photos/502/225",
        videoUrl: "https://www.youtube.com/watch?v=iONDebHX9qk",
        duration: "9:50",
        rating: 4.8,
        views: 22000,
        upvotes: 720,
        downvotes: 9,
        tags: ["productivity", "time-management"],
        author: "OpenCourse",
    },
    {
        id: "n4",
        title: "How to Build Discipline",
        description: "Practical steps to build long-term self-discipline.",
        thumbnail: "https://picsum.photos/503/225",
        videoUrl: "https://www.youtube.com/watch?v=JzE6hJfZlKU",
        duration: "11:05",
        rating: 4.7,
        views: 19500,
        upvotes: 640,
        downvotes: 13,
        tags: ["discipline", "self-growth"],
        author: "Community",
    },
    {
        id: "n5",
        title: "Resume & Interview Preparation",
        description: "How to crack interviews and write impactful resumes.",
        thumbnail: "https://picsum.photos/504/225",
        videoUrl: "https://www.youtube.com/watch?v=HG68Ymazo18",
        duration: "14:30",
        rating: 4.6,
        views: 17000,
        upvotes: 520,
        downvotes: 21,
        tags: ["career", "interview"],
        author: "OpenCourse",
    },
    {
        id: "n6",
        title: "Personal Finance Basics",
        description: "Understand saving, investing, and budgeting.",
        thumbnail: "https://picsum.photos/505/225",
        videoUrl: "https://www.youtube.com/watch?v=H3z9PBljE1U",
        duration: "13:10",
        rating: 4.8,
        views: 24000,
        upvotes: 800,
        downvotes: 11,
        tags: ["finance", "money"],
        author: "Community",
    },
    {
        id: "n7",
        title: "Mindset for Long-Term Success",
        description: "Develop a growth mindset for personal and professional life.",
        thumbnail: "https://picsum.photos/506/225",
        videoUrl: "https://www.youtube.com/watch?v=KQ8Sx8KjK7I",
        duration: "10:00",
        rating: 4.9,
        views: 26000,
        upvotes: 900,
        downvotes: 7,
        tags: ["mindset", "self-improvement"],
        author: "OpenCourse",
    },
];


export const mockContent: DomainContent = {
    tech: [
        {
            id: "web-dev",
            title: "Web Development",
            subtopics: [
                {
                    id: "javascript",
                    title: "JavaScript",
                    miniTopics: [
                        { id: "hoisting", title: "Hoisting", videos: mockVideos },
                        { id: "closures", title: "Closures", videos: mockVideos },
                        { id: "async", title: "Async Programming", videos: mockVideos.slice(3, 5) },
                    ],
                },
                {
                    id: "react",
                    title: "React",
                    miniTopics: [
                        { id: "hooks", title: "Hooks", videos: mockVideos.slice(5, 7) },
                        { id: "state", title: "State Management", videos: mockVideos.slice(7, 8) },
                    ],
                },
            ],
        },
        {
            id: "backend",
            title: "Backend Development",
            subtopics: [
                {
                    id: "node",
                    title: "Node.js",
                    miniTopics: [
                        { id: "node-basics", title: "Node Basics", videos: mockVideos.slice(9, 11) },
                    ],
                },
                {
                    id: "database",
                    title: "Databases",
                    miniTopics: [
                        { id: "mongodb", title: "MongoDB", videos: mockVideos.slice(11, 12) },
                    ],
                },
            ],
        },
        {
            id: "devops",
            title: "DevOps",
            subtopics: [
                {
                    id: "tools",
                    title: "Tools",
                    miniTopics: [
                        { id: "git", title: "Git & GitHub", videos: mockVideos.slice(12, 13) },
                        { id: "docker", title: "Docker", videos: mockVideos.slice(14, 15) },
                    ],
                },
            ],
        },
    ],
    nonTech: [
        {
            id: "soft-skills",
            title: "Soft Skills",
            subtopics: [
                {
                    id: "communication",
                    title: "Communication",
                    miniTopics: [
                        {
                            id: "effective-communication",
                            title: "Effective Communication",
                            videos: nonTechVideos.slice(0, 2),
                        },
                    ],
                },
            ],
        },
        {
            id: "productivity",
            title: "Productivity",
            subtopics: [
                {
                    id: "time-management",
                    title: "Time Management",
                    miniTopics: [
                        {
                            id: "time-skills",
                            title: "Managing Time",
                            videos: nonTechVideos.slice(2, 4),
                        },
                    ],
                },
            ],
        },
        {
            id: "career",
            title: "Career Development",
            subtopics: [
                {
                    id: "job-prep",
                    title: "Job Preparation",
                    miniTopics: [
                        {
                            id: "interviews",
                            title: "Interviews & Resume",
                            videos: nonTechVideos.slice(4, 5),
                        },
                    ],
                },
            ],
        },
        {
            id: "finance",
            title: "Personal Finance",
            subtopics: [
                {
                    id: "money-basics",
                    title: "Money Management",
                    miniTopics: [
                        {
                            id: "finance-basics",
                            title: "Finance Basics",
                            videos: nonTechVideos.slice(5, 6),
                        },
                    ],
                },
            ],
        },
        {
            id: "mindset",
            title: "Mindset & Growth",
            subtopics: [
                {
                    id: "growth",
                    title: "Growth Mindset",
                    miniTopics: [
                        {
                            id: "success-mindset",
                            title: "Mindset for Success",
                            videos: nonTechVideos
                        },
                    ],
                },
            ],
        },
    ],
};

